#! /bin/bash

if [ -f /etc/environment ]; then
  . /etc/environment
fi

export PATH="${PATH}:${HOME}/favorite-configuration/scripts/"

alias ll='ls -l'
alias rr='rm -vrf'
alias remmina='GDK_BACKEND=x11 remmina'
alias rm-empty='find ./ -depth -type d -empty -exec rm -v -r {} \;'
alias bashrc='vim ${HOME}/.bashrc && source ${HOME}/.bashrc'
alias cputemp='watch -n 1 vcgencmd measure_temp'
alias sd='sudo shutdown now'
alias uefi='sudo systemctl reboot --firmware-setup'

if [ $UID -eq 0 ]; then
  PS1="\[\e]0;\u@\h: \w\a\]\[\033[;94m\]┌──${debian_chroot:+($debian_chroot)──}${VIRTUAL_ENV:+(\[\033[0;1m\]$(basename $VIRTUAL_ENV)\[\033[;94m\])}(\[\033[1;31m\]\u@\h\[\033[;94m\])-[\[\033[0;1m\]\w\[\033[;94m\]]\n\[\033[;94m\]└─\[\033[1;31m\]\\$\[\033[0m\] "
else
  PS1="\[\e]0;\u@\h: \w\a\]\[\033[;32m\]┌──${debian_chroot:+($debian_chroot)──}${VIRTUAL_ENV:+(\[\033[0;1m\]$(basename $VIRTUAL_ENV)\[\033[;32m\])}(\[\033[1;34m\]\u@\h\[\033[;32m\])-[\[\033[0;1m\]\w\[\033[;32m\]]\n\[\033[;32m\]└─\[\033[1;34m\]\\$\[\033[0m\] "
fi

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  fi
fi

echo "" > $HOME/.bash_history
echo "" > $HOME/.history

