#! /bin/bash

function _BASH_COMPLETION_FFMPEG_VIDEO() {
  local cur prev words cword split
  _init_completion || return
  local defaultIFS=$' \t\n'
  local IFS=$defaultIFS
  if [ "${cword}" = "1" ]; then
    COMPREPLY=($(compgen -W '--input-file --no-reconnect --start --end --variable-frame-rate --no-audio --rotate --crop --aspect' -- "$cur"))
  fi
}
complete -F _BASH_COMPLETION_FFMPEG_VIDEO ffmpeg-video
