#! /bin/bash

if [ $# -ge 1 ]; then
  n16=$(cat /dev/urandom | tr -dc '1-9' | head -c16)
  opt=""
  opt="${opt} -err_detect ignore_err"
  opt="${opt} -fflags +discardcorrupt"
  if [ $# -eq 1 ]; then
    opt="${opt} -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 30"
  else
    opt="${opt} $2"
  fi
  conf=""
  conf="${conf} -tag:v hvc1 -movflags +faststart"
  conf="${conf} -max_muxing_queue_size 9999"
  conf="${conf} -c:v libx265 -level:v 4.0"
  conf="${conf} -b_strategy 2 -bf 2"
  conf="${conf} -flags cgop -coder ac -pix_fmt yuv420p -crf 20"
  conf="${conf} -r 25 -bufsize 10M"
  conf="${conf} -map 0:a:0 -c:a aac -aac_coder twoloop -ac 2 -ar 48000"
  conf="${conf} -map 0:v:0 -map_chapters -1 -map -0:s -map_metadata -1"
  conf="${conf} -fflags +bitexact -flags:v +bitexact -flags:a +bitexact"
  # conf="${conf} -vf crop=1440:1080"
  echo "ffmpeg ${opt} -i \"$1\" ${conf} ${n16}.mp4"
  ffmpeg ${opt} -i "$1" ${conf} ${n16}.mp4
  chmod 600 ${n16}.mp4
fi

