#! /bin/bash

if [ $# -ge 1 ]; then
  n16=$(cat /dev/urandom | tr -dc '1-9' | head -c16)
  opt="-err_detect ignore_err"
  opt="${opt} -fflags +discardcorrupt"
  if [ $# -ge 2 ] && [ "$2" != "" ]; then
    opt="${opt} $2"
  else
    opt="${opt} -reconnect 1 -reconnect_streamed 1 -reconnect_at_eof 1 -reconnect_delay_max 30"
    opt="${opt} -http_persistent 0 -multiple_requests 1 "
    opt="${opt} -timeout 5000000 -rw_timeout 5000000"
  fi
  conf="-tag:v hvc1 -movflags +faststart"
  conf="${conf} -max_muxing_queue_size 9999"
  conf="${conf} -c:v libx265 -level:v 4.0"
  conf="${conf} -b_strategy 2 -bf 2"
  conf="${conf} -flags cgop -coder ac -pix_fmt yuv420p -crf 20"
  conf="${conf} -bufsize 10M"
  if [ $# -ge 3 ] && [ "$3" != "" ]; then
    conf="${conf} $3"
  else
    conf="${conf} -map 0:a:0 -c:a aac -aac_coder twoloop -ac 2 -ar 48000"
  fi
  conf="${conf} -map 0:v:0 -map_chapters -1 -map -0:s -map_metadata -1"
  conf="${conf} -fflags +bitexact -flags:v +bitexact -flags:a +bitexact"
  if [ $# -ge 4 ] && [ "$4" != "" ]; then 
    conf="${conf} -vf crop=$4"
  fi
  if [ $# -ge 5 ] && [ "$5" != "" ]; then
    conf="${conf} -aspect $5"
  fi
  echo "ffmpeg ${opt} -i \"$1\" ${conf} ${n16}.mp4"
  ffmpeg ${opt} -i "$1" ${conf} ${n16}.mp4
  echo "chmod 600 ${n16}.mp4"
  chmod 600 ${n16}.mp4
else
  echo "ffmpeg-video <src> <opt> <conf> <crop> <aspect>"
fi

